# Generated by Django 5.0.7 on 2024-07-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="account",
            new_name="account_id",
        ),
    ]
