# Generated by Django 5.0.6 on 2024-07-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_account_transaction_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название счета"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.account",
                verbose_name="Идентификатор счета",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма операции"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания транзакции"
            ),
        ),
    ]
