# Generated by Django 5.0.7 on 2024-07-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0003_alter_account_name_alter_transaction_account_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания транзакции"
            ),
        ),
    ]
