# Generated by Django 5.0.7 on 2024-07-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="account_id",
            new_name="account",
        ),
    ]
