# Generated by Django 5.0.7 on 2024-07-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_rename_account_id_transaction_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ("id",),
                "verbose_name": "Счёт",
                "verbose_name_plural": "Счета",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ("-date",),
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
            },
        ),
    ]
